# Task 0: Thiết lập Môi trường và Tải Dữ liệu

In [3]:
import tarfile
import os

tar_path = '../../data/lab6/hwu.tar.gz'
extract_path = '../../data/lab6/'

if os.path.exists(tar_path):
    with tarfile.open(tar_path, 'r:gz') as tar:
        tar.extractall(path=extract_path)
        print(f"Extracted {tar_path} to {extract_path}")
        print("Extracted files:", tar.getnames())
else:
    print(f"File not found: {tar_path}")

print("\nContents of data/lab6/:")
for item in os.listdir('../../data/lab6'):
    print(f"  {item}")

Extracted ../../data/lab6/hwu.tar.gz to ../../data/lab6/
Extracted files: ['hwu', 'hwu/categories.json', 'hwu/train_5.csv', 'hwu/train_10.csv', 'hwu/val.csv', 'hwu/test.csv', 'hwu/train.csv']

Contents of data/lab6/:
  hwu
  hwu.tar.gz
  nlu.csv

In [4]:
import os

expected_files = ['train.csv', 'val.csv', 'test.csv']
missing_files = []

for file in expected_files:
    file_path = f'../../data/lab6/hwu/{file}'
    if os.path.exists(file_path):
        print(f"✓ Found: {file}")
    else:
        print(f"✗ Missing: {file}")
        missing_files.append(file)

if missing_files:
    print(f"\nMissing files: {missing_files}")
    print("Make sure the extraction completed successfully in the previous cell.")
else:
    print("\n✓ All expected files found! Ready to load data.")

✓ Found: train.csv
✓ Found: val.csv
✓ Found: test.csv

✓ All expected files found! Ready to load data.

In [5]:
import pandas as pd
extract_path = '../../data/lab6/hwu/'
# Dữ liệu có thể được phân tách bằng tab và không có header
df_train = pd.read_csv(f'{extract_path}train.csv', sep=',', header=None, names=['text', 'intent'])
df_val = pd.read_csv(f'{extract_path}val.csv', sep=',', header=None, names=['text', 'intent'])
df_test = pd.read_csv(f'{extract_path}test.csv', sep=',', header=None, names=['text', 'intent'])
print("Train shape:", df_train.shape)
print("Validation shape:", df_val.shape)
print("Test shape:", df_test.shape)
df_train.head()

Train shape: (8955, 2)
Validation shape: (1077, 2)
Test shape: (1077, 2)

                                                text       intent
0                                               text     category
1                what alarms do i have set right now  alarm_query
2                    checkout today alarm of meeting  alarm_query
3                              report alarm settings  alarm_query
4  see see for me the alarms that you have set to...  alarm_query

In [6]:
# Preprocessing intent -> numeric
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(df_train['intent'])

df_train['intent_encoded'] = encoder.transform(df_train['intent'])
df_val['intent_encoded'] = encoder.transform(df_val['intent'])
df_test['intent_encoded'] = encoder.transform(df_test['intent'])

for index, class_label in enumerate(encoder.classes_):
    print(f"{index}: '{class_label}'")
df_train.head()

0: 'alarm_query'
1: 'alarm_remove'
2: 'alarm_set'
3: 'audio_volume_down'
4: 'audio_volume_mute'
5: 'audio_volume_up'
6: 'calendar_query'
7: 'calendar_remove'
8: 'calendar_set'
9: 'category'
10: 'cooking_recipe'
11: 'datetime_convert'
12: 'datetime_query'
13: 'email_addcontact'
14: 'email_query'
15: 'email_querycontact'
16: 'email_sendemail'
17: 'general_affirm'
18: 'general_commandstop'
19: 'general_confirm'
20: 'general_dontcare'
21: 'general_explain'
22: 'general_joke'
23: 'general_negate'
24: 'general_praise'
25: 'general_quirky'
26: 'general_repeat'
27: 'iot_cleaning'
28: 'iot_coffee'
29: 'iot_hue_lightchange'
30: 'iot_hue_lightdim'
31: 'iot_hue_lightoff'
32: 'iot_hue_lighton'
33: 'iot_hue_lightup'
34: 'iot_wemo_off'
35: 'iot_wemo_on'
36: 'lists_createoradd'
37: 'lists_query'
38: 'lists_remove'
39: 'music_likeness'
40: 'music_query'
41: 'music_settings'
42: 'news_query'
43: 'play_audiobook'
44: 'play_game'
45: 'play_music'
46: 'play_podcasts'
47: 'play_radio'
48: 'qa_currency'
49: 'qa_definition'
50: 'qa_factoid'
51: 'qa_maths'
52: 'qa_stock'
53: 'recommendation_events'
54: 'recommendation_locations'
55: 'recommendation_movies'
56: 'social_post'
57: 'social_query'
58: 'takeaway_order'
59: 'takeaway_query'
60: 'transport_query'
61: 'transport_taxi'
62: 'transport_ticket'
63: 'transport_traffic'
64: 'weather_query'

,text,intent,intent_encoded
0,text,category,9
1,what alarms do i have set right now,alarm_query,0
2,checkout today alarm of meeting,alarm_query,0
3,report alarm settings,alarm_query,0
4,see see for me the alarms that you have set to...,alarm_query,0

In [7]:
print("\nNumber of unique categories:", df_train['intent_encoded'].nunique())
print("\nCategory distribution:")
print(df_train['intent_encoded'].value_counts().head(10))

Number of unique categories: 65

Category distribution:
intent_encoded
2     159
56    159
49    159
25    158
42    158
29    158
20    158
6     158
0     158
18    158
Name: count, dtype: int64

# Task 1: TF-IDF + Logistic Regression

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report
# 1. Tạo một pipeline với TfidfVectorizer và LogisticRegression
tfidf_lr_pipeline = make_pipeline(
    TfidfVectorizer(max_features=5000),
    LogisticRegression(max_iter=1000)
)
# 2. Train model
tfidf_lr_pipeline.fit(df_train['text'], df_train['intent_encoded'])
# 3. Đánh giá model
val_preds = tfidf_lr_pipeline.predict(df_val['text'])
print(classification_report(df_val['intent_encoded'], val_preds))

              precision    recall  f1-score   support

           0       0.78      0.95      0.86        19
           1       1.00      0.55      0.71        11
           2       0.76      0.84      0.80        19
           3       0.62      0.62      0.62         8
           4       1.00      0.53      0.70        15
           5       0.79      0.85      0.81        13
           6       0.75      0.47      0.58        19
           7       0.82      0.95      0.88        19
           8       0.88      0.79      0.83        19
           9       0.00      0.00      0.00         1
          10       0.94      0.89      0.92        19
          11       0.56      0.62      0.59         8
          12       0.82      0.74      0.78        19
          13       1.00      0.88      0.93         8
          14       0.94      0.89      0.92        19
          15       0.94      0.84      0.89        19
          16       0.86      0.95      0.90        19
          17       1.00      0.89      0.94        19
          18       0.90      0.95      0.92        19
          19       1.00      1.00      1.00        19
          20       1.00      1.00      1.00        19
          21       1.00      0.95      0.97        19
          22       1.00      0.83      0.91        12
          23       0.83      1.00      0.90        19
          24       0.83      1.00      0.90        19
          25       0.42      0.58      0.49        19
          26       1.00      0.95      0.97        19
          27       1.00      0.88      0.93        16
          28       1.00      0.95      0.97        19
          29       0.83      1.00      0.90        19
          30       0.91      0.83      0.87        12
          31       0.85      0.89      0.87        19
          32       0.00      0.00      0.00         3
          33       0.80      0.86      0.83        14
          34       0.88      0.78      0.82         9
          35       0.75      0.86      0.80         7
          36       0.86      1.00      0.93        19
          37       0.74      0.89      0.81        19
          38       0.94      0.79      0.86        19
          39       0.88      0.78      0.82        18
          40       0.77      0.89      0.83        19
          41       0.80      0.57      0.67         7
          42       0.89      0.89      0.89        19
          43       0.83      0.79      0.81        19
          44       0.89      0.84      0.86        19
          45       0.67      0.63      0.65        19
          46       0.95      0.95      0.95        19
          47       0.89      0.89      0.89        19
          48       0.95      0.95      0.95        19
          49       0.90      0.95      0.92        19
          50       0.76      0.68      0.72        19
          51       0.79      0.79      0.79        14
          52       1.00      0.89      0.94        19
          53       0.75      0.79      0.77        19
          54       0.68      1.00      0.81        19
          55       0.89      0.80      0.84        10
          56       0.94      0.84      0.89        19
          57       0.85      0.94      0.89        18
          58       0.94      0.84      0.89        19
          59       0.90      0.95      0.92        19
          60       0.83      0.79      0.81        19
          61       1.00      0.94      0.97        18
          62       0.90      1.00      0.95        19
          63       0.94      0.89      0.92        19
          64       0.86      1.00      0.93        19

    accuracy                           0.86      1077
   macro avg       0.84      0.82      0.83      1077
weighted avg       0.87      0.86      0.86      1077

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [43]:
# In ra "kiến trúc" của pipeline
print(tfidf_lr_pipeline)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer(max_features=5000)),
                ('logisticregression', LogisticRegression(max_iter=1000))])

# Task 2: Pipeline Word2Vec (Trung bình) + Dense Layer

In [10]:
%load_ext tensorboard

In [11]:
from tensorflow.keras.callbacks import TensorBoard
import datetime

log_dir = "../../results/lab6/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

# 2. Tạo callback
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [12]:
import numpy as np
from gensim.models import Word2Vec
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

In [13]:
# 1. Huấn luyện mô hình Word2Vec trên dữ liệu text của bạn
train_sentences = [text.split() for text in df_train['text']]
w2v_model = Word2Vec(train_sentences, vector_size=100, window=5, min_count=1, workers=4)

In [14]:
train_sentences[:5]

[['text'],
 ['what', 'alarms', 'do', 'i', 'have', 'set', 'right', 'now'],
 ['checkout', 'today', 'alarm', 'of', 'meeting'],
 ['report', 'alarm', 'settings'],
 ['see',
  'see',
  'for',
  'me',
  'the',
  'alarms',
  'that',
  'you',
  'have',
  'set',
  'tomorrow',
  'morning']]

In [15]:
# 2. Viết hàm để chuyển mỗi câu thành vector trung bình
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
STOP_WORDS = set(stopwords.words('english'))
def sentence_to_avg_vector(text, model):
    vector_size = model.vector_size
    words = text.split()
    word_vectors = []
    for word in words:
        word_lower = word.lower()
        if word_lower in STOP_WORDS:
            continue
        if word_lower in model.wv:  # model.wv chứa tất cả các vector từ
            word_vectors.append(model.wv[word_lower])
    if not word_vectors:
        return np.zeros(vector_size, dtype=np.float32)
    avg_vector = np.mean(word_vectors, axis=0)
    return avg_vector

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [16]:
# 3. Chuyển đổi tất cả các câu trong tập train, val, test thành vectors
X_train = np.array([sentence_to_avg_vector(text, w2v_model) for text in df_train['text']])
X_val = np.array([sentence_to_avg_vector(text, w2v_model) for text in df_val['text']])
X_test = np.array([sentence_to_avg_vector(text, w2v_model) for text in df_test['text']])

y_train = df_train['intent_encoded'].values
y_val = df_val['intent_encoded'].values
y_test = df_test['intent_encoded'].values

print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)

X_train shape: (8955, 100)
X_val shape: (1077, 100)
X_test shape: (1077, 100)
y_train shape: (8955,)

In [17]:
# 4. Xây dựng mô hình Sequential của Keras (3 hidden layers)
num_classes = len(encoder.classes_)
model = Sequential([
    Dense(256, activation='relu', input_shape=(w2v_model.vector_size,)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(128, activation='relu', kernel_regularizer='l2'),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    BatchNormalization(),

    Dense(num_classes, activation='softmax')
])

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
from tensorflow.keras.optimizers import Adam

# 5.1. Compile
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 256)            │        25,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 65)             │         4,225 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 73,025 (285.25 KB)

 Trainable params: 72,129 (281.75 KB)

 Non-trainable params: 896 (3.50 KB)

In [19]:
# 5.2. Huấn luyện + đánh giá
from tensorflow.keras.callbacks import EarlyStopping
history = model.fit(X_train, y_train,
                    epochs=50, # Thử 50 epochs
                    batch_size=256,
                    validation_data=(X_val, y_val),
                    callbacks = [EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True), tensorboard_callback],
                    verbose=1)

print("\n--- Đánh giá trên tập Test ---")
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - accuracy: 0.0614 - loss: 5.5381 - val_accuracy: 0.0334 - val_loss: 5.2102
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1280 - loss: 4.4687 - val_accuracy: 0.0334 - val_loss: 4.8328
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2102 - loss: 3.7821 - val_accuracy: 0.0362 - val_loss: 4.6224
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2891 - loss: 3.2571 - val_accuracy: 0.0176 - val_loss: 4.5037
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3367 - loss: 2.9129 - val_accuracy: 0.0223 - val_loss: 4.4414
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3851 - loss: 2.6241 - val_accuracy: 0.0316 - val_loss: 4.3811
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.4213 - loss: 2.4350 - val_accuracy: 0.0316 - val_loss: 4.2941
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.4293 - loss: 2.3047 - val_accuracy: 0.0316 - val_loss: 4.2262
Epoch 9/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.4534 - loss: 2.1774 - val_accuracy: 0.0566 - val_loss: 4.1180
Epoch 10/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4623 - loss: 2.0965 - val_accuracy: 0.0371 - val_loss: 3.9458
Epoch 11/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.4790 - loss: 2.0088 - val_accuracy: 0.1003 - val_loss: 3.7815
Epoch 12/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.4824 - loss: 1.9707 - val_accuracy: 0.1226 - val_loss: 3.7005
Epoch 13/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4969 - loss: 1.9099 - val_accuracy: 0.1597 - val_loss: 3.3966
Epoch 14/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4963 - loss: 1.8671 - val_accuracy: 0.2173 - val_loss: 3.1191
Epoch 15/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5037 - loss: 1.8464 - val_accuracy: 0.2646 - val_loss: 2.7727
Epoch 16/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5151 - loss: 1.7942 - val_accuracy: 0.1755 - val_loss: 3.1286
Epoch 17/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5114 - loss: 1.7892 - val_accuracy: 0.3909 - val_loss: 2.3626
Epoch 18/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5273 - loss: 1.7576 - val_accuracy: 0.4197 - val_loss: 2.1966
Epoch 19/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5351 - loss: 1.7123 - val_accuracy: 0.3705 - val_loss: 2.2457
Epoch 20/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5358 - loss: 1.6994 - val_accuracy: 0.4819 - val_loss: 1.9497
Epoch 21/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5310 - loss: 1.6879 - val_accuracy: 0.2683 - val_loss: 2.9030
Epoch 22/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5300 - loss: 1.6839 - val_accuracy: 0.4475 - val_loss: 2.0415
Epoch 23/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5439 - loss: 1.6697 - val_accuracy: 0.4503 - val_loss: 2.1256
Epoch 24/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5458 - loss: 1.6479 - val_accuracy: 0.4615 - val_loss: 1.9223
Epoch 25/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5513 - loss: 1.6387 - val_accuracy: 0.5255 - val_loss: 1.7162
Epoch 26/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5496 - loss: 1.6255 - val_accuracy: 0.4754 - val_loss: 1.8541
Epoch 27/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5490 - loss: 1.6099 - val_accuracy: 0.3965 - val_loss: 2.4089
Epoch 28/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5540 - loss: 1.6050 - val_accuracy: 0.3825 - val_loss: 2.2282
Epoch 29/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5597 - loss: 1.6103 - val_accuracy: 0.4364 - val_loss: 2.0109
Epoch 30/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5561 - loss: 1.5900 - val_accuracy: 0.5227 - val_loss: 1.6800
Epoch 31/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5611 - loss: 1.5855 - val_accuracy: 0.4559 - val_loss: 2.0187
Epoch 32/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5592 - loss: 1.5769 - val_accuracy: 0.3835 - val_loss: 2.2321
Epoch 33/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5704 - loss: 1.5481 - val_accuracy: 0.4578 - val_loss: 1.9981
Epoch 34/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5550 - loss: 1.5788 - val_accuracy: 0.4011 - val_loss: 2.4504
Epoch 35/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5652 - loss: 1.5488 - val_accuracy: 0.4448 - val_loss: 2.1376
Epoch 36/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5653 - loss: 1.5630 - val_accuracy: 0.4355 - val_loss: 2.2264
Epoch 37/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5704 - loss: 1.5323 - val_accuracy: 0.5292 - val_loss: 1.6381
Epoch 38/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5780 - loss: 1.5135 - val_accuracy: 0.5840 - val_loss: 1.5032
Epoch 39/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5769 - loss: 1.5184 - val_accuracy: 0.4615 - val_loss: 2.1197
Epoch 40/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5799 - loss: 1.4927 - val_accuracy: 0.4383 - val_loss: 2.1190
Epoch 41/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5773 - loss: 1.5066 - val_accuracy: 0.3983 - val_loss: 2.4602
Epoch 42/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5795 - loss: 1.4918 - val_accuracy: 0.4977 - val_loss: 1.8963
Epoch 43/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.5815 - loss: 1.4894 - val_accuracy: 0.5209 - val_loss: 1.7542
Epoch 44/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5752 - loss: 1.4889 - val_accuracy: 0.4308 - val_loss: 2.1434
Epoch 45/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.5765 - loss: 1.5013 - val_accuracy: 0.5552 - val_loss: 1.6547
Epoch 46/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5858 - loss: 1.4675 - val_accuracy: 0.5655 - val_loss: 1.5445
Epoch 47/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5916 - loss: 1.4471 - val_accuracy: 0.4392 - val_loss: 2.2081
Epoch 48/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5913 - loss: 1.4432 - val_accuracy: 0.4373 - val_loss: 2.0937
Epoch 49/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5838 - loss: 1.4808 - val_accuracy: 0.4113 - val_loss: 2.3353
Epoch 50/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5883 - loss: 1.4531 - val_accuracy: 0.4076 - val_loss: 2.2033

--- Đánh giá trên tập Test ---
Test Loss: 1.5633
Test Accuracy: 0.5552

In [20]:
print("\n--- Đánh giá chi tiết trên tập Test ---")

y_pred_probabilities = model.predict(X_test)
y_pred_classes = np.argmax(y_pred_probabilities, axis=1)
y_true_classes = y_test 
target_names = encoder.classes_

print(classification_report(y_true_classes, y_pred_classes, target_names=target_names))

--- Đánh giá chi tiết trên tập Test ---
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
                          precision    recall  f1-score   support

             alarm_query       1.00      0.58      0.73        19
            alarm_remove       0.88      0.64      0.74        11
               alarm_set       0.52      0.63      0.57        19
       audio_volume_down       0.00      0.00      0.00         8
       audio_volume_mute       0.50      0.53      0.52        15
         audio_volume_up       0.50      0.62      0.55        13
          calendar_query       0.09      0.05      0.07        19
         calendar_remove       0.77      0.89      0.83        19
            calendar_set       0.25      0.53      0.34        19
                category       0.00      0.00      0.00         1
          cooking_recipe       0.39      0.47      0.43        19
        datetime_convert       0.71      0.62      0.67         8
          datetime_query       0.46      0.68      0.55        19
        email_addcontact       0.58      0.88      0.70         8
             email_query       0.44      0.58      0.50        19
      email_querycontact       0.28      0.47      0.35        19
         email_sendemail       0.32      0.79      0.45        19
          general_affirm       0.59      0.89      0.71        19
     general_commandstop       1.00      0.79      0.88        19
         general_confirm       0.90      1.00      0.95        19
        general_dontcare       0.86      0.95      0.90        19
         general_explain       1.00      0.21      0.35        19
            general_joke       1.00      0.67      0.80        12
          general_negate       0.92      0.63      0.75        19
          general_praise       1.00      0.58      0.73        19
          general_quirky       0.18      0.11      0.13        19
          general_repeat       0.71      0.79      0.75        19
            iot_cleaning       0.88      0.88      0.88        16
              iot_coffee       0.66      1.00      0.79        19
     iot_hue_lightchange       0.75      0.63      0.69        19
        iot_hue_lightdim       0.50      0.17      0.25        12
        iot_hue_lightoff       0.41      0.74      0.53        19
         iot_hue_lighton       0.00      0.00      0.00         3
         iot_hue_lightup       0.33      0.14      0.20        14
            iot_wemo_off       0.00      0.00      0.00         9
             iot_wemo_on       0.25      0.86      0.39         7
       lists_createoradd       0.65      0.79      0.71        19
             lists_query       0.80      0.63      0.71        19
            lists_remove       0.48      0.74      0.58        19
          music_likeness       0.48      0.56      0.51        18
             music_query       0.53      0.47      0.50        19
          music_settings       1.00      0.14      0.25         7
              news_query       0.40      0.53      0.45        19
          play_audiobook       0.29      0.63      0.40        19
               play_game       0.60      0.47      0.53        19
              play_music       0.28      0.26      0.27        19
           play_podcasts       1.00      0.47      0.64        19
              play_radio       0.69      0.58      0.63        19
             qa_currency       0.72      0.95      0.82        19
           qa_definition       0.33      0.05      0.09        19
              qa_factoid       0.11      0.21      0.14        19
                qa_maths       0.67      0.71      0.69        14
                qa_stock       0.94      0.84      0.89        19
   recommendation_events       0.88      0.37      0.52        19
recommendation_locations       0.57      0.21      0.31        19
   recommendation_movies       0.50      0.20      0.29        10
             social_post       1.00      0.05      0.10        19
            social_query       0.38      0.17      0.23        18
          takeaway_order       0.67      0.63      0.65        19
          takeaway_query       1.00      0.37      0.54        19
         transport_query       0.88      0.37      0.52        19
          transport_taxi       0.53      0.89      0.67        18
        transport_ticket       0.71      0.79      0.75        19
       transport_traffic       0.89      0.89      0.89        19
           weather_query       0.57      0.42      0.48        19

                accuracy                           0.56      1077
               macro avg       0.59      0.53      0.51      1077
            weighted avg       0.61      0.56      0.54      1077

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# Task 3: Embedding Pre-trained + LSTM

In [21]:
! pip install tensorflow.keras

Requirement already satisfied: tensorflow.keras in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.1)

In [22]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Input, Bidirectional

In [23]:
# 1. Tiền xử lý cho mô hình chuỗi
## 1.1 Tokenizer: Tạo vocab và chuyển text thành chuỗi chỉ số
vocab_size = 5000
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<UNK>")
tokenizer.fit_on_texts(df_train['text'])
train_sequences = tokenizer.texts_to_sequences(df_train['text'])
val_sequences = tokenizer.texts_to_sequences(df_val['text'])
test_sequences = tokenizer.texts_to_sequences(df_test['text'])

In [24]:
print(train_sequences[:5])

[[920], [9, 99, 24, 5, 26, 35, 92, 62], [809, 39, 36, 15, 113], [606, 36, 532], [265, 265, 12, 4, 2, 99, 27, 8, 26, 35, 89, 138]]

In [25]:
max = np.max([len(seq) for seq in train_sequences])
print(max)

25

In [26]:
# 1.2. Padding: Đảm bảo các chuỗi có cùng độ dài
max_len = 30
X_train_pad = pad_sequences(train_sequences, maxlen=max_len, padding='post')
# ... (Tương tự cho val và test)
X_val_pad = pad_sequences(val_sequences, maxlen=max_len, padding='post')
X_test_pad = pad_sequences(test_sequences, maxlen=max_len, padding='post')

In [27]:
# 2. Tạo ma trận trọng số cho Embedding Layer từ Word2Vec
vocab_size = len(tokenizer.word_index) + 1
embedding_dim = w2v_model.vector_size
embedding_matrix = np.zeros((vocab_size, embedding_dim))
for word, i in tokenizer.word_index.items():
    if word in w2v_model.wv:
        embedding_matrix[i] = w2v_model.wv[word]

print(embedding_matrix.shape)
print(max_len)
print(vocab_size)

(4265, 100)
30
4265

In [28]:
# 3. Xây dựng mô hình Sequential với LSTM
max_len = 30
vocab_size = len(tokenizer.word_index) + 1
lstm_model_pretrained = Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim,
        weights=[embedding_matrix],
        input_length=max_len,
        trainable=False  # Đóng băng embedding layer
    ),
    LSTM(128, dropout=0.2, recurrent_dropout=0),
    Dense(num_classes, activation='softmax')
])
lstm_model_pretrained.build(input_shape=(None, max_len))
lstm_model_pretrained.compile(loss='sparse_categorical_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])
print(lstm_model_pretrained.summary())

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 30, 100)        │       426,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 128)            │       117,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 65)             │         8,385 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 552,133 (2.11 MB)

 Trainable params: 125,633 (490.75 KB)

 Non-trainable params: 426,500 (1.63 MB)

None

In [29]:
from tensorflow.keras.callbacks import EarlyStopping

lstm_model_pretrained.fit(X_train_pad, y_train,
                    epochs=50, 
                    batch_size=256,
                    validation_data=(X_val_pad, y_val),
                    callbacks=[EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True), tensorboard_callback]
                   )

Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - accuracy: 0.0191 - loss: 4.1432 - val_accuracy: 0.0334 - val_loss: 4.0868
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - accuracy: 0.0350 - loss: 4.0661 - val_accuracy: 0.0381 - val_loss: 4.0045
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - accuracy: 0.0366 - loss: 4.0025 - val_accuracy: 0.0474 - val_loss: 3.9036
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - accuracy: 0.0515 - loss: 3.8944 - val_accuracy: 0.0566 - val_loss: 3.8216
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - accuracy: 0.0521 - loss: 3.8343 - val_accuracy: 0.0678 - val_loss: 3.7507
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.0577 - loss: 3.7929 - val_accuracy: 0.0650 - val_loss: 3.7337
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - accuracy: 0.0672 - loss: 3.7203 - val_accuracy: 0.0687 - val_loss: 3.6122
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - accuracy: 0.0784 - loss: 3.6327 - val_accuracy: 0.1049 - val_loss: 3.5130
Epoch 9/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - accuracy: 0.0879 - loss: 3.5739 - val_accuracy: 0.1114 - val_loss: 3.4484
Epoch 10/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - accuracy: 0.1071 - loss: 3.5003 - val_accuracy: 0.1272 - val_loss: 3.3726
Epoch 11/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - accuracy: 0.1171 - loss: 3.4109 - val_accuracy: 0.1411 - val_loss: 3.2967
Epoch 12/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.1215 - loss: 3.3851 - val_accuracy: 0.1383 - val_loss: 3.3190
Epoch 13/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.1190 - loss: 3.3679 - val_accuracy: 0.1551 - val_loss: 3.2371
Epoch 14/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.1350 - loss: 3.3143 - val_accuracy: 0.1504 - val_loss: 3.2635
Epoch 15/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.1398 - loss: 3.2639 - val_accuracy: 0.1755 - val_loss: 3.1200
Epoch 16/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - accuracy: 0.1479 - loss: 3.2401 - val_accuracy: 0.1746 - val_loss: 3.1045
Epoch 17/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.1511 - loss: 3.1960 - val_accuracy: 0.1718 - val_loss: 3.0810
Epoch 18/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - accuracy: 0.1541 - loss: 3.1741 - val_accuracy: 0.1959 - val_loss: 3.0301
Epoch 19/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.1569 - loss: 3.1729 - val_accuracy: 0.1876 - val_loss: 3.0435
Epoch 20/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - accuracy: 0.1637 - loss: 3.1386 - val_accuracy: 0.1829 - val_loss: 3.0507
Epoch 21/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - accuracy: 0.1709 - loss: 3.1092 - val_accuracy: 0.1978 - val_loss: 3.0005
Epoch 22/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.1696 - loss: 3.1119 - val_accuracy: 0.1941 - val_loss: 3.0236
Epoch 23/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - accuracy: 0.1720 - loss: 3.0894 - val_accuracy: 0.2006 - val_loss: 2.9783
Epoch 24/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - accuracy: 0.1777 - loss: 3.0694 - val_accuracy: 0.1829 - val_loss: 3.0345
Epoch 25/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - accuracy: 0.1731 - loss: 3.0782 - val_accuracy: 0.2154 - val_loss: 2.9468
Epoch 26/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - accuracy: 0.1755 - loss: 3.0653 - val_accuracy: 0.2015 - val_loss: 2.9187
Epoch 27/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - accuracy: 0.1835 - loss: 3.0266 - val_accuracy: 0.2256 - val_loss: 2.8981
Epoch 28/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.1886 - loss: 3.0075 - val_accuracy: 0.2145 - val_loss: 2.8861
Epoch 29/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.1850 - loss: 3.0075 - val_accuracy: 0.2275 - val_loss: 2.8807
Epoch 30/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.1933 - loss: 2.9949 - val_accuracy: 0.2145 - val_loss: 2.8797
Epoch 31/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.1873 - loss: 2.9983 - val_accuracy: 0.2256 - val_loss: 2.8285
Epoch 32/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.1929 - loss: 2.9658 - val_accuracy: 0.2303 - val_loss: 2.8544
Epoch 33/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.1953 - loss: 2.9684 - val_accuracy: 0.2340 - val_loss: 2.8146
Epoch 34/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.1924 - loss: 2.9617 - val_accuracy: 0.2210 - val_loss: 2.8181
Epoch 35/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.1941 - loss: 2.9525 - val_accuracy: 0.2405 - val_loss: 2.8206
Epoch 36/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.1978 - loss: 2.9504 - val_accuracy: 0.2368 - val_loss: 2.8124
Epoch 37/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.2001 - loss: 2.9108 - val_accuracy: 0.2526 - val_loss: 2.7976
Epoch 38/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - accuracy: 0.2035 - loss: 2.9170 - val_accuracy: 0.2182 - val_loss: 2.8606
Epoch 39/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - accuracy: 0.2048 - loss: 2.9096 - val_accuracy: 0.2358 - val_loss: 2.8077
Epoch 40/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - accuracy: 0.2071 - loss: 2.8954 - val_accuracy: 0.2433 - val_loss: 2.7487
Epoch 41/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - accuracy: 0.2171 - loss: 2.8629 - val_accuracy: 0.2488 - val_loss: 2.7546
Epoch 42/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.2166 - loss: 2.8685 - val_accuracy: 0.2266 - val_loss: 2.8239
Epoch 43/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - accuracy: 0.2183 - loss: 2.8398 - val_accuracy: 0.2461 - val_loss: 2.7329
Epoch 44/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.2179 - loss: 2.8586 - val_accuracy: 0.2433 - val_loss: 2.7346
Epoch 45/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - accuracy: 0.2154 - loss: 2.8671 - val_accuracy: 0.2433 - val_loss: 2.7189
Epoch 46/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - accuracy: 0.2210 - loss: 2.8316 - val_accuracy: 0.2321 - val_loss: 2.7384
Epoch 47/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - accuracy: 0.2315 - loss: 2.8113 - val_accuracy: 0.2813 - val_loss: 2.6850
Epoch 48/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - accuracy: 0.2352 - loss: 2.7701 - val_accuracy: 0.2804 - val_loss: 2.6304
Epoch 49/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.2304 - loss: 2.7941 - val_accuracy: 0.2618 - val_loss: 2.6515
Epoch 50/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.2317 - loss: 2.7786 - val_accuracy: 0.2507 - val_loss: 2.6666

In [40]:
# Test trên tập test
loss, accuracy = lstm_model_pretrained.evaluate(X_test_pad, y_test, verbose=1)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

y_pred_probabilities = lstm_model_pretrained.predict(X_test_pad)
y_pred_classes = np.argmax(y_pred_probabilities, axis=1)

target_names = encoder.classes_
print(classification_report(y_test, y_pred_classes, 
                            target_names=target_names, 
                            zero_division=0))

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2730 - loss: 2.6828
Test Loss: 2.6828
Test Accuracy: 0.2730
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
                          precision    recall  f1-score   support

             alarm_query       0.63      0.63      0.63        19
            alarm_remove       0.73      0.73      0.73        11
               alarm_set       0.89      0.84      0.86        19
       audio_volume_down       0.50      0.12      0.20         8
       audio_volume_mute       0.18      0.13      0.15        15
         audio_volume_up       0.00      0.00      0.00        13
          calendar_query       0.00      0.00      0.00        19
         calendar_remove       0.35      0.42      0.38        19
            calendar_set       0.17      0.26      0.20        19
                category       0.00      0.00      0.00         1
          cooking_recipe       0.14      0.11      0.12        19
        datetime_convert       0.50      0.38      0.43         8
          datetime_query       0.22      0.53      0.31        19
        email_addcontact       0.15      0.25      0.19         8
             email_query       0.15      0.21      0.17        19
      email_querycontact       0.25      0.05      0.09        19
         email_sendemail       0.16      0.26      0.20        19
          general_affirm       0.29      0.53      0.37        19
     general_commandstop       0.62      0.68      0.65        19
         general_confirm       0.70      0.84      0.76        19
        general_dontcare       0.15      0.16      0.15        19
         general_explain       0.30      0.47      0.37        19
            general_joke       0.40      0.33      0.36        12
          general_negate       0.23      0.53      0.32        19
          general_praise       0.38      0.16      0.22        19
          general_quirky       0.10      0.05      0.07        19
          general_repeat       0.43      0.16      0.23        19
            iot_cleaning       0.46      0.69      0.55        16
              iot_coffee       0.47      0.37      0.41        19
     iot_hue_lightchange       0.35      0.63      0.45        19
        iot_hue_lightdim       0.18      0.33      0.24        12
        iot_hue_lightoff       0.56      0.74      0.64        19
         iot_hue_lighton       0.00      0.00      0.00         3
         iot_hue_lightup       0.00      0.00      0.00        14
            iot_wemo_off       0.00      0.00      0.00         9
             iot_wemo_on       0.20      0.14      0.17         7
       lists_createoradd       0.38      0.42      0.40        19
             lists_query       0.21      0.21      0.21        19
            lists_remove       0.21      0.21      0.21        19
          music_likeness       0.00      0.00      0.00        18
             music_query       0.09      0.11      0.10        19
          music_settings       0.00      0.00      0.00         7
              news_query       0.06      0.05      0.05        19
          play_audiobook       0.05      0.05      0.05        19
               play_game       0.22      0.53      0.31        19
              play_music       0.17      0.05      0.08        19
           play_podcasts       0.18      0.37      0.25        19
              play_radio       0.14      0.05      0.08        19
             qa_currency       0.19      0.53      0.28        19
           qa_definition       0.19      0.16      0.17        19
              qa_factoid       0.28      0.26      0.27        19
                qa_maths       0.00      0.00      0.00        14
                qa_stock       0.25      0.11      0.15        19
   recommendation_events       0.31      0.21      0.25        19
recommendation_locations       0.00      0.00      0.00        19
   recommendation_movies       0.00      0.00      0.00        10
             social_post       0.20      0.37      0.26        19
            social_query       0.08      0.11      0.09        18
          takeaway_order       0.00      0.00      0.00        19
          takeaway_query       0.19      0.32      0.24        19
         transport_query       0.05      0.05      0.05        19
          transport_taxi       0.29      0.22      0.25        18
        transport_ticket       0.55      0.58      0.56        19
       transport_traffic       0.00      0.00      0.00        19
           weather_query       0.00      0.00      0.00        19

                accuracy                           0.27      1077
               macro avg       0.23      0.26      0.23      1077
            weighted avg       0.24      0.27      0.24      1077

# Task 4: Embedding học từ đầu + LSTM

In [35]:
# 1. Xây dựng mô hình
lstm_model_scratch = Sequential([
    Embedding(vocab_size, 200, input_length=max_len),
    LSTM(128, dropout=0.3, recurrent_dropout=0.3),
    BatchNormalization(),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

In [36]:
# 2. Compile, huấn luyện (sử dụng EarlyStopping) và đánh giá
lstm_model_scratch.compile(loss='sparse_categorical_crossentropy',
                optimizer=Adam(learning_rate=0.001),
                metrics=['accuracy'])

lstm_model_scratch.build(input_shape=(None, max_len))
lstm_model_scratch.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 30, 200)        │       853,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 128)            │       168,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 65)             │         8,385 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,030,345 (3.93 MB)

 Trainable params: 1,030,089 (3.93 MB)

 Non-trainable params: 256 (1.00 KB)

In [37]:
early_stopping = EarlyStopping(
    monitor='val_loss', 
    patience=10, 
    restore_best_weights=True
)
callbacks_list = [early_stopping, tensorboard_callback]

In [38]:
history = lstm_model_scratch.fit(
    X_train_pad, y_train,
    epochs=50,            
    batch_size=256,
    validation_data=(X_val_pad, y_val),
    callbacks=callbacks_list,  
    verbose=1
    )

Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - accuracy: 0.0150 - loss: 4.2510 - val_accuracy: 0.0176 - val_loss: 4.1664
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.0237 - loss: 4.1615 - val_accuracy: 0.0362 - val_loss: 4.1558
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.0710 - loss: 3.7621 - val_accuracy: 0.2396 - val_loss: 4.0115
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.1648 - loss: 3.1493 - val_accuracy: 0.4002 - val_loss: 3.6735
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.2288 - loss: 2.7267 - val_accuracy: 0.5348 - val_loss: 2.9944
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.3040 - loss: 2.3673 - val_accuracy: 0.5812 - val_loss: 2.4696
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.3592 - loss: 2.0816 - val_accuracy: 0.6230 - val_loss: 1.9678
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.4409 - loss: 1.7957 - val_accuracy: 0.6806 - val_loss: 1.5540
Epoch 9/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.4948 - loss: 1.5848 - val_accuracy: 0.6639 - val_loss: 1.2688
Epoch 10/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.5455 - loss: 1.4318 - val_accuracy: 0.7233 - val_loss: 1.0843
Epoch 11/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.6021 - loss: 1.2448 - val_accuracy: 0.7205 - val_loss: 0.9963
Epoch 12/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.6533 - loss: 1.0941 - val_accuracy: 0.7567 - val_loss: 0.9208
Epoch 13/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.6939 - loss: 0.9587 - val_accuracy: 0.7846 - val_loss: 0.8956
Epoch 14/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.7426 - loss: 0.8246 - val_accuracy: 0.7595 - val_loss: 0.9080
Epoch 15/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.7832 - loss: 0.7161 - val_accuracy: 0.7846 - val_loss: 0.8388
Epoch 16/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.8114 - loss: 0.6181 - val_accuracy: 0.7920 - val_loss: 0.8372
Epoch 17/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.8401 - loss: 0.5382 - val_accuracy: 0.8087 - val_loss: 0.7907
Epoch 18/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.8676 - loss: 0.4704 - val_accuracy: 0.8134 - val_loss: 0.8016
Epoch 19/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.8806 - loss: 0.4191 - val_accuracy: 0.8180 - val_loss: 0.7762
Epoch 20/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.8941 - loss: 0.3790 - val_accuracy: 0.8171 - val_loss: 0.7775
Epoch 21/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9089 - loss: 0.3283 - val_accuracy: 0.8357 - val_loss: 0.7588
Epoch 22/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.9129 - loss: 0.3072 - val_accuracy: 0.8162 - val_loss: 0.7868
Epoch 23/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.9274 - loss: 0.2697 - val_accuracy: 0.8162 - val_loss: 0.7953
Epoch 24/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.9308 - loss: 0.2503 - val_accuracy: 0.8338 - val_loss: 0.7728
Epoch 25/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.9347 - loss: 0.2310 - val_accuracy: 0.8319 - val_loss: 0.7844
Epoch 26/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9466 - loss: 0.2011 - val_accuracy: 0.8338 - val_loss: 0.7681
Epoch 27/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.9503 - loss: 0.1884 - val_accuracy: 0.8310 - val_loss: 0.7780
Epoch 28/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9535 - loss: 0.1675 - val_accuracy: 0.8338 - val_loss: 0.7964
Epoch 29/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9550 - loss: 0.1667 - val_accuracy: 0.8245 - val_loss: 0.8173
Epoch 30/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9585 - loss: 0.1543 - val_accuracy: 0.8227 - val_loss: 0.8030
Epoch 31/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9615 - loss: 0.1429 - val_accuracy: 0.8199 - val_loss: 0.8104

In [41]:
loss, accuracy = lstm_model_scratch.evaluate(X_test_pad, y_test, verbose=0)

print(f"Test Loss    : {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f} ({(accuracy*100):.2f}%)")

y_pred_probabilities = lstm_model_scratch.predict(X_test_pad)
y_pred_classes = np.argmax(y_pred_probabilities, axis=1)

target_names = encoder.classes_
print(classification_report(y_test, y_pred_classes, 
                            target_names=target_names, 
                            zero_division=0))

Test Loss    : 0.7899
Test Accuracy: 0.8078 (80.78%)
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
                          precision    recall  f1-score   support

             alarm_query       0.85      0.89      0.87        19
            alarm_remove       1.00      0.91      0.95        11
               alarm_set       0.82      0.95      0.88        19
       audio_volume_down       0.75      0.75      0.75         8
       audio_volume_mute       1.00      0.80      0.89        15
         audio_volume_up       0.81      1.00      0.90        13
          calendar_query       0.35      0.42      0.38        19
         calendar_remove       0.76      1.00      0.86        19
            calendar_set       0.76      0.68      0.72        19
                category       0.00      0.00      0.00         1
          cooking_recipe       0.75      0.63      0.69        19
        datetime_convert       0.70      0.88      0.78         8
          datetime_query       0.80      0.84      0.82        19
        email_addcontact       0.75      0.75      0.75         8
             email_query       0.80      0.84      0.82        19
      email_querycontact       0.50      0.47      0.49        19
         email_sendemail       0.77      0.89      0.83        19
          general_affirm       1.00      1.00      1.00        19
     general_commandstop       1.00      1.00      1.00        19
         general_confirm       0.95      1.00      0.97        19
        general_dontcare       0.95      0.95      0.95        19
         general_explain       0.95      0.95      0.95        19
            general_joke       1.00      1.00      1.00        12
          general_negate       0.79      1.00      0.88        19
          general_praise       0.95      1.00      0.97        19
          general_quirky       0.20      0.26      0.23        19
          general_repeat       0.86      1.00      0.93        19
            iot_cleaning       1.00      0.94      0.97        16
              iot_coffee       1.00      0.95      0.97        19
     iot_hue_lightchange       0.93      0.68      0.79        19
        iot_hue_lightdim       0.57      1.00      0.73        12
        iot_hue_lightoff       1.00      0.95      0.97        19
         iot_hue_lighton       0.00      0.00      0.00         3
         iot_hue_lightup       1.00      0.71      0.83        14
            iot_wemo_off       0.86      0.67      0.75         9
             iot_wemo_on       0.75      0.86      0.80         7
       lists_createoradd       0.89      0.89      0.89        19
             lists_query       0.76      0.84      0.80        19
            lists_remove       0.94      0.84      0.89        19
          music_likeness       0.71      0.56      0.62        18
             music_query       0.71      0.63      0.67        19
          music_settings       1.00      0.43      0.60         7
              news_query       0.75      0.63      0.69        19
          play_audiobook       0.94      0.84      0.89        19
               play_game       1.00      0.63      0.77        19
              play_music       0.63      0.63      0.63        19
           play_podcasts       0.94      0.89      0.92        19
              play_radio       0.73      0.84      0.78        19
             qa_currency       0.95      0.95      0.95        19
           qa_definition       0.65      0.79      0.71        19
              qa_factoid       0.30      0.37      0.33        19
                qa_maths       0.87      0.93      0.90        14
                qa_stock       1.00      0.89      0.94        19
   recommendation_events       0.74      0.74      0.74        19
recommendation_locations       0.75      0.63      0.69        19
   recommendation_movies       1.00      0.80      0.89        10
             social_post       0.95      1.00      0.97        19
            social_query       0.84      0.89      0.86        18
          takeaway_order       0.79      0.79      0.79        19
          takeaway_query       0.83      0.79      0.81        19
         transport_query       0.70      0.74      0.72        19
          transport_taxi       0.95      1.00      0.97        18
        transport_ticket       0.94      0.79      0.86        19
       transport_traffic       0.95      0.95      0.95        19
           weather_query       0.87      0.68      0.76        19

                accuracy                           0.81      1077
               macro avg       0.80      0.78      0.79      1077
            weighted avg       0.82      0.81      0.81      1077

# Task 5: Đánh giá, So sánh và Phân tích

In [45]:
tensorboard --logdir log_dir

Reusing TensorBoard on port 6006 (pid 29328), started 9:30:15 ago. (Use '!kill 29328' to kill it.)

In [49]:
# Tổng hợp kết quả các model bao gồm loss
from sklearn.metrics import accuracy_score, classification_report, log_loss
import numpy as np

print("=== TỔNG HỢP KẾT QUẢ CÁC MODEL (bao gồm Loss) ===\n")

# 1. TF-IDF + LogReg (từ validation set)
print("1. TF-IDF + Logistic Regression:")
val_preds_tfidf = tfidf_lr_pipeline.predict(df_val['text'])
val_proba_tfidf = tfidf_lr_pipeline.predict_proba(df_val['text'])
val_accuracy_tfidf = accuracy_score(df_val['intent_encoded'], val_preds_tfidf)
val_loss_tfidf = log_loss(df_val['intent_encoded'], val_proba_tfidf)
report_tfidf = classification_report(df_val['intent_encoded'], val_preds_tfidf, output_dict=True)
print(f"   Validation Accuracy: {val_accuracy_tfidf:.4f}")
print(f"   Validation Loss: {val_loss_tfidf:.4f}")
print(f"   Macro F1-score: {report_tfidf['macro avg']['f1-score']:.4f}")
print(f"   Weighted F1-score: {report_tfidf['weighted avg']['f1-score']:.4f}")

# 2. Word2Vec + Dense NN (đã có kết quả từ cell trước)
print("\n2. Word2Vec + Dense NN:")
print(f"   Test Accuracy: 0.5600")  # từ output trước
print(f"   Test Loss: N/A")  # không có loss được lưu
print(f"   Macro F1-score: 0.5100") # từ output trước
print(f"   Weighted F1-score: 0.5400") # từ output trước

# 3. Pre-trained Word2Vec + LSTM
print("\n3. Pre-trained Word2Vec + LSTM:")
test_loss_pretrained, test_acc_pretrained = lstm_model_pretrained.evaluate(X_test_pad, y_test, verbose=0)
print(f"   Test Accuracy: {test_acc_pretrained:.4f}")
print(f"   Test Loss: {test_loss_pretrained:.4f}")
print(f"   Macro F1-score: 0.2300") # từ output trước
print(f"   Weighted F1-score: 0.2400") # từ output trước

# 4. Embedding từ đầu + LSTM
print("\n4. Embedding từ đầu + LSTM:")
test_loss_scratch, test_acc_scratch = lstm_model_scratch.evaluate(X_test_pad, y_test, verbose=0)
print(f"   Test Accuracy: {test_acc_scratch:.4f}")
print(f"   Test Loss: {test_loss_scratch:.4f}")
print(f"   Macro F1-score: 0.7900") # từ output trước
print(f"   Weighted F1-score: 0.8100") # từ output trước

print("\n=== SUMMARY TABLE FOR REPORT ===")
print("| Model | Accuracy | Loss | Macro F1 | Weighted F1 |")
print("|-------|----------|------|----------|-------------|")
print(f"| TF-IDF+LogReg | {val_accuracy_tfidf:.4f} | {val_loss_tfidf:.4f} | {report_tfidf['macro avg']['f1-score']:.4f} | {report_tfidf['weighted avg']['f1-score']:.4f} |")
print(f"| Word2Vec+Dense | 0.5600 | N/A | 0.5100 | 0.5400 |")
print(f"| Pretrained+LSTM | {test_acc_pretrained:.4f} | {test_loss_pretrained:.4f} | 0.2300 | 0.2400 |")
print(f"| Scratch+LSTM | {test_acc_scratch:.4f} | {test_loss_scratch:.4f} | 0.7900 | 0.8100 |")

=== TỔNG HỢP KẾT QUẢ CÁC MODEL (bao gồm Loss) ===

1. TF-IDF + Logistic Regression:
   Validation Accuracy: 0.8589
   Validation Loss: 0.9800
   Macro F1-score: 0.8251
   Weighted F1-score: 0.8567

2. Word2Vec + Dense NN:
   Test Accuracy: 0.5600
   Test Loss: N/A
   Macro F1-score: 0.5100
   Weighted F1-score: 0.5400

3. Pre-trained Word2Vec + LSTM:

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

   Test Accuracy: 0.2730
   Test Loss: 2.6828
   Macro F1-score: 0.2300
   Weighted F1-score: 0.2400

4. Embedding từ đầu + LSTM:
   Test Accuracy: 0.8078
   Test Loss: 0.7899
   Macro F1-score: 0.7900
   Weighted F1-score: 0.8100

=== SUMMARY TABLE FOR REPORT ===
| Model | Accuracy | Loss | Macro F1 | Weighted F1 |
|-------|----------|------|----------|-------------|
| TF-IDF+LogReg | 0.8589 | 0.9800 | 0.8251 | 0.8567 |
| Word2Vec+Dense | 0.5600 | N/A | 0.5100 | 0.5400 |
| Pretrained+LSTM | 0.2730 | 2.6828 | 0.2300 | 0.2400 |
| Scratch+LSTM | 0.8078 | 0.7899 | 0.7900 | 0.8100 |
   Test Accuracy: 0.8078
   Test Loss: 0.7899
   Macro F1-score: 0.7900
   Weighted F1-score: 0.8100

=== SUMMARY TABLE FOR REPORT ===
| Model | Accuracy | Loss | Macro F1 | Weighted F1 |
|-------|----------|------|----------|-------------|
| TF-IDF+LogReg | 0.8589 | 0.9800 | 0.8251 | 0.8567 |
| Word2Vec+Dense | 0.5600 | N/A | 0.5100 | 0.5400 |
| Pretrained+LSTM | 0.2730 | 2.6828 | 0.2300 | 0.2400 |
| Scratch+LSTM | 0.8078 | 0.7899 | 0.7900 | 0.8100 |

In [52]:
# Thêm vài câu ví dụ "khó" / thường gặp vào danh sách user_examples
user_examples = [
    ("can you remind me to not call my mom", "reminder_create"),
    ("is it going to be sunny or rainy tomorrow", "weather_query"),
    ("find a flight from new york to london but not through paris", "flight_search"),
    ("Can you please set an alarm for me tomorrow morning at 6 AM", "alarm_set"),
    ("Don't play music right now", "general_commandstop"),
    ("Weather today", "weather_query"),
]

# Hàm tiện lợi để in top-k dự đoán (label, prob)
def topk_from_probas(probas, k=3):
    idxs = np.argsort(probas)[::-1][:k]
    labels = encoder.inverse_transform(idxs)
    return [(labels[i], float(probas[idxs[i]])) for i in range(len(idxs))]

for text, true_label in user_examples:
    print("="*80)
    print(f"Input: {text!r}")
    # True label -> index (nếu có)
    try:
        true_idx = int(encoder.transform([true_label])[0])
    except Exception:
        true_idx = None
    print(f"True label: {true_label} (encoded: {true_idx})")

    # 1) TF-IDF + LogisticRegression
    tf_pred_idx = int(tfidf_lr_pipeline.predict([text])[0])
    tf_proba = tfidf_lr_pipeline.predict_proba([text])[0]
    tf_pred_label = encoder.inverse_transform([tf_pred_idx])[0]
    tf_pred_prob = float(tf_proba[tf_pred_idx])
    tf_top3 = topk_from_probas(tf_proba, k=3)
    print(f"TF-IDF+LR -> {tf_pred_label} (idx {tf_pred_idx}, prob {tf_pred_prob:.4f})", "OK" if true_idx==tf_pred_idx else "WRONG")
    print(f"   top3: {tf_top3}")

    # 2) Word2Vec (avg) + Dense NN (variable name: model)
    vec = sentence_to_avg_vector(text, w2v_model)
    w2v_proba = model.predict(np.array([vec]), verbose=0)[0]
    w2v_idx = int(np.argmax(w2v_proba))
    w2v_label = encoder.inverse_transform([w2v_idx])[0]
    w2v_prob = float(w2v_proba[w2v_idx])
    w2v_top3 = topk_from_probas(w2v_proba, k=3)
    print(f"Word2Vec+Dense -> {w2v_label} (idx {w2v_idx}, prob {w2v_prob:.4f})", "OK" if true_idx==w2v_idx else "WRONG")
    print(f"   top3: {w2v_top3}")

    # 3) Pretrained Word2Vec embedding + LSTM
    seq = tokenizer.texts_to_sequences([text])
    pad = pad_sequences(seq, maxlen=max_len, padding='post')
    pre_proba = lstm_model_pretrained.predict(pad, verbose=0)[0]
    pre_idx = int(np.argmax(pre_proba))
    pre_label = encoder.inverse_transform([pre_idx])[0]
    pre_prob = float(pre_proba[pre_idx])
    pre_top3 = topk_from_probas(pre_proba, k=3)
    print(f"PretrainedEmbedding+LSTM -> {pre_label} (idx {pre_idx}, prob {pre_prob:.4f})", "OK" if true_idx==pre_idx else "WRONG")
    print(f"   top3: {pre_top3}")

    # 4) Embedding (scratch) + LSTM
    pad2 = pad  # reuse pad
    scr_proba = lstm_model_scratch.predict(pad2, verbose=0)[0]
    scr_idx = int(np.argmax(scr_proba))
    scr_label = encoder.inverse_transform([scr_idx])[0]
    scr_prob = float(scr_proba[scr_idx])
    scr_top3 = topk_from_probas(scr_proba, k=3)
    print(f"ScratchEmbedding+LSTM -> {scr_label} (idx {scr_idx}, prob {scr_prob:.4f})", "OK" if true_idx==scr_idx else "WRONG")
    print(f"   top3: {scr_top3}")

================================================================================
Input: 'can you remind me to not call my mom'
True label: reminder_create (encoded: None)
TF-IDF+LR -> calendar_set (idx 8, prob 0.3335) WRONG
   top3: [('calendar_set', 0.333538858079335), ('email_querycontact', 0.07068064281273394), ('general_negate', 0.053637147084640194)]
Word2Vec+Dense -> calendar_set (idx 8, prob 0.3210) WRONG
   top3: [('calendar_set', 0.3210252821445465), ('email_sendemail', 0.22479769587516785), ('email_query', 0.11238753795623779)]
PretrainedEmbedding+LSTM -> social_post (idx 56, prob 0.0986) WRONG
   top3: [('social_post', 0.09857174009084702), ('takeaway_order', 0.07268866151571274), ('recommendation_locations', 0.05791664123535156)]
ScratchEmbedding+LSTM -> calendar_set (idx 8, prob 0.9835) WRONG
   top3: [('calendar_set', 0.9834993481636047), ('alarm_set', 0.005007795058190823), ('email_querycontact', 0.003914648201316595)]
================================================================================
Input: 'is it going to be sunny or rainy tomorrow'
True label: weather_query (encoded: 64)
TF-IDF+LR -> weather_query (idx 64, prob 0.4928) OK
   top3: [('weather_query', 0.4927975123143633), ('general_quirky', 0.025729100025353623), ('takeaway_query', 0.019822680791678544)]
Word2Vec+Dense -> calendar_set (idx 8, prob 0.3633) WRONG
   top3: [('calendar_set', 0.363308846950531), ('weather_query', 0.12163352966308594), ('calendar_query', 0.09268669784069061)]
ScratchEmbedding+LSTM -> calendar_set (idx 8, prob 0.9835) WRONG
   top3: [('calendar_set', 0.9834993481636047), ('alarm_set', 0.005007795058190823), ('email_querycontact', 0.003914648201316595)]
================================================================================
Input: 'is it going to be sunny or rainy tomorrow'
True label: weather_query (encoded: 64)
TF-IDF+LR -> weather_query (idx 64, prob 0.4928) OK
   top3: [('weather_query', 0.4927975123143633), ('general_quirky', 0.025729100025353623), ('takeaway_query', 0.019822680791678544)]
Word2Vec+Dense -> calendar_set (idx 8, prob 0.3633) WRONG
   top3: [('calendar_set', 0.363308846950531), ('weather_query', 0.12163352966308594), ('calendar_query', 0.09268669784069061)]
PretrainedEmbedding+LSTM -> social_query (idx 57, prob 0.0870) WRONG
   top3: [('social_query', 0.0870087742805481), ('qa_currency', 0.08059781789779663), ('email_query', 0.08009102195501328)]
ScratchEmbedding+LSTM -> weather_query (idx 64, prob 0.9952) OK
   top3: [('weather_query', 0.9952124357223511), ('recommendation_events', 0.0011397196212783456), ('calendar_query', 0.001043858123011887)]
================================================================================
Input: 'find a flight from new york to london but not through paris'
True label: flight_search (encoded: None)
TF-IDF+LR -> general_negate (idx 23, prob 0.0784) WRONG
   top3: [('general_negate', 0.0784212946647784), ('transport_query', 0.06641361569989314), ('transport_ticket', 0.04780801903919778)]
Word2Vec+Dense -> lists_createoradd (idx 36, prob 0.1531) WRONG
   top3: [('lists_createoradd', 0.15309622883796692), ('email_querycontact', 0.10457152128219604), ('email_query', 0.09667180478572845)]
PretrainedEmbedding+LSTM -> social_query (idx 57, prob 0.0870) WRONG
   top3: [('social_query', 0.0870087742805481), ('qa_currency', 0.08059781789779663), ('email_query', 0.08009102195501328)]
ScratchEmbedding+LSTM -> weather_query (idx 64, prob 0.9952) OK
   top3: [('weather_query', 0.9952124357223511), ('recommendation_events', 0.0011397196212783456), ('calendar_query', 0.001043858123011887)]
================================================================================
Input: 'find a flight from new york to london but not through paris'
True label: flight_search (encoded: None)
TF-IDF+LR -> general_negate (idx 23, prob 0.0784) WRONG
   top3: [('general_negate', 0.0784212946647784), ('transport_query', 0.06641361569989314), ('transport_ticket', 0.04780801903919778)]
Word2Vec+Dense -> lists_createoradd (idx 36, prob 0.1531) WRONG
   top3: [('lists_createoradd', 0.15309622883796692), ('email_querycontact', 0.10457152128219604), ('email_query', 0.09667180478572845)]
PretrainedEmbedding+LSTM -> email_addcontact (idx 13, prob 0.1247) WRONG
   top3: [('email_addcontact', 0.12469203770160675), ('email_sendemail', 0.1206672266125679), ('transport_ticket', 0.07899320125579834)]
ScratchEmbedding+LSTM -> social_post (idx 56, prob 0.8672) WRONG
   top3: [('social_post', 0.8671748638153076), ('takeaway_query', 0.04636126384139061), ('general_joke', 0.014535295777022839)]
================================================================================
Input: 'Can you please set an alarm for me tomorrow morning at 6 AM'
True label: alarm_set (encoded: 2)
TF-IDF+LR -> alarm_set (idx 2, prob 0.8982) OK
   top3: [('alarm_set', 0.8982445147203301), ('alarm_query', 0.05068069327178745), ('alarm_remove', 0.010565043071959794)]
Word2Vec+Dense -> alarm_set (idx 2, prob 0.7295) OK
   top3: [('alarm_set', 0.7294842600822449), ('alarm_remove', 0.13263830542564392), ('alarm_query', 0.10174357891082764)]
PretrainedEmbedding+LSTM -> alarm_set (idx 2, prob 0.8971) OK
   top3: [('alarm_set', 0.8970758318901062), ('alarm_remove', 0.038107018917798996), ('alarm_query', 0.02271927520632744)]
PretrainedEmbedding+LSTM -> email_addcontact (idx 13, prob 0.1247) WRONG
   top3: [('email_addcontact', 0.12469203770160675), ('email_sendemail', 0.1206672266125679), ('transport_ticket', 0.07899320125579834)]
ScratchEmbedding+LSTM -> social_post (idx 56, prob 0.8672) WRONG
   top3: [('social_post', 0.8671748638153076), ('takeaway_query', 0.04636126384139061), ('general_joke', 0.014535295777022839)]
================================================================================
Input: 'Can you please set an alarm for me tomorrow morning at 6 AM'
True label: alarm_set (encoded: 2)
TF-IDF+LR -> alarm_set (idx 2, prob 0.8982) OK
   top3: [('alarm_set', 0.8982445147203301), ('alarm_query', 0.05068069327178745), ('alarm_remove', 0.010565043071959794)]
Word2Vec+Dense -> alarm_set (idx 2, prob 0.7295) OK
   top3: [('alarm_set', 0.7294842600822449), ('alarm_remove', 0.13263830542564392), ('alarm_query', 0.10174357891082764)]
PretrainedEmbedding+LSTM -> alarm_set (idx 2, prob 0.8971) OK
   top3: [('alarm_set', 0.8970758318901062), ('alarm_remove', 0.038107018917798996), ('alarm_query', 0.02271927520632744)]
ScratchEmbedding+LSTM -> alarm_set (idx 2, prob 0.9691) OK
   top3: [('alarm_set', 0.9691010117530823), ('alarm_query', 0.024929560720920563), ('alarm_remove', 0.004101866390556097)]
================================================================================
Input: "Don't play music right now"
True label: general_commandstop (encoded: 18)
TF-IDF+LR -> play_music (idx 45, prob 0.6405) WRONG
   top3: [('play_music', 0.6404512093516869), ('music_query', 0.0567381892309755), ('play_game', 0.04050743822291063)]
Word2Vec+Dense -> play_music (idx 45, prob 0.4385) WRONG
   top3: [('play_music', 0.4385470747947693), ('play_audiobook', 0.36798128485679626), ('music_query', 0.08662702888250351)]
ScratchEmbedding+LSTM -> alarm_set (idx 2, prob 0.9691) OK
   top3: [('alarm_set', 0.9691010117530823), ('alarm_query', 0.024929560720920563), ('alarm_remove', 0.004101866390556097)]
================================================================================
Input: "Don't play music right now"
True label: general_commandstop (encoded: 18)
TF-IDF+LR -> play_music (idx 45, prob 0.6405) WRONG
   top3: [('play_music', 0.6404512093516869), ('music_query', 0.0567381892309755), ('play_game', 0.04050743822291063)]
Word2Vec+Dense -> play_music (idx 45, prob 0.4385) WRONG
   top3: [('play_music', 0.4385470747947693), ('play_audiobook', 0.36798128485679626), ('music_query', 0.08662702888250351)]
PretrainedEmbedding+LSTM -> news_query (idx 42, prob 0.0712) WRONG
   top3: [('news_query', 0.07121782004833221), ('social_query', 0.06594052165746689), ('play_podcasts', 0.06553507596254349)]
ScratchEmbedding+LSTM -> play_music (idx 45, prob 0.9348) WRONG
   top3: [('play_music', 0.9348189234733582), ('music_settings', 0.02708571031689644), ('music_query', 0.013974444009363651)]
================================================================================
Input: 'Weather today'
True label: weather_query (encoded: 64)
TF-IDF+LR -> weather_query (idx 64, prob 0.9728) OK
   top3: [('weather_query', 0.9728435549394705), ('general_quirky', 0.0034926757083954324), ('news_query', 0.001802376943248439)]
Word2Vec+Dense -> weather_query (idx 64, prob 0.6296) OK
   top3: [('weather_query', 0.6295713186264038), ('transport_traffic', 0.19530756771564484), ('calendar_query', 0.05068524181842804)]
PretrainedEmbedding+LSTM -> news_query (idx 42, prob 0.0712) WRONG
   top3: [('news_query', 0.07121782004833221), ('social_query', 0.06594052165746689), ('play_podcasts', 0.06553507596254349)]
ScratchEmbedding+LSTM -> play_music (idx 45, prob 0.9348) WRONG
   top3: [('play_music', 0.9348189234733582), ('music_settings', 0.02708571031689644), ('music_query', 0.013974444009363651)]
================================================================================
Input: 'Weather today'
True label: weather_query (encoded: 64)
TF-IDF+LR -> weather_query (idx 64, prob 0.9728) OK
   top3: [('weather_query', 0.9728435549394705), ('general_quirky', 0.0034926757083954324), ('news_query', 0.001802376943248439)]
Word2Vec+Dense -> weather_query (idx 64, prob 0.6296) OK
   top3: [('weather_query', 0.6295713186264038), ('transport_traffic', 0.19530756771564484), ('calendar_query', 0.05068524181842804)]
PretrainedEmbedding+LSTM -> news_query (idx 42, prob 0.0982) WRONG
   top3: [('news_query', 0.09819681197404861), ('qa_definition', 0.059663496911525726), ('social_query', 0.05749868229031563)]
ScratchEmbedding+LSTM -> weather_query (idx 64, prob 0.9954) OK
   top3: [('weather_query', 0.9954406023025513), ('transport_query', 0.0012649893760681152), ('email_query', 0.0011801475193351507)]
PretrainedEmbedding+LSTM -> news_query (idx 42, prob 0.0982) WRONG
   top3: [('news_query', 0.09819681197404861), ('qa_definition', 0.059663496911525726), ('social_query', 0.05749868229031563)]
ScratchEmbedding+LSTM -> weather_query (idx 64, prob 0.9954) OK
   top3: [('weather_query', 0.9954406023025513), ('transport_query', 0.0012649893760681152), ('email_query', 0.0011801475193351507)]

In [53]:
print("Kiểm tra quick:")
print("num_classes variable:", num_classes)
print("encoder.classes_ length:", len(encoder.classes_))
print("Test set intent distribution:")
print(df_test['intent'].value_counts())

Kiểm tra quick:
num_classes variable: 65
encoder.classes_ length: 65
Test set intent distribution:
intent
weather_query          19
general_repeat         19
iot_hue_lightchange    19
transport_traffic      19
alarm_query            19
                       ..
email_addcontact        8
music_settings          7
iot_wemo_on             7
iot_hue_lighton         3
category                1
Name: count, Length: 65, dtype: int64